pycms_controller:
  path: 培优接口用例.xlsx
  sheet: CMS接口T
  finishRowNo: 9
#  req_url: 6
#  req_method: 5
#  req_header: 8
#  req_params: 9
#  req_expect: 10
#  req_relation: 11
#  req_remark: 4
#  req_url2: 7
saas_controller:
  path: 金斗云接口测试用例.xlsx
  sheet: saas
  startRowNo: 4
#  finishRowNo: 8
  finishRowNo: 6
  req_url: 6
  req_method: 5
  req_header: 7
  req_params: 8
  req_expect: 9
  req_relation: 10
  req_remark: 4
  req_sql: 11
  req_user: 12
  parameterization: 13
mysql:
  host: 10.10.200.173
  port: 3306
  name: peiyou
  user: education
  password: lexue123
pre:
  host: 10.10.200.210
  port: 3306
  name: peiyou
  user: education
  password: lexue123
tsl:
  host: 10.10.200.173
  port: 3306
  name: peiyou
  user: education
  password: lexue123
dev:
  host: 10.10.200.173
  port: 3306
  name: peiyou
  user: education
  password: lexue123

sas:
  host: 10.10.200.173
  port: 3306
  name: peiyou
  user: education
  password: lexue123