#!/bin/bash    
#    
# chkconfig: 345 80 20    
# description: start the integration service   
#    
# Source function library    
#. /etc/rc.d/init.d/functions    

JAVA_HOME=/usr/local/java/jdk1.8.0_131  
export JAVA_HOME    

case "$1" in
start)    
    echo "Starting Integration..."    
    cd /home/instore/xueersi/integration && nohup $JAVA_HOME/bin/java -Xms1024M -Xmx1024M -Djava.ext.dirs=lib com.hanshows.cdi.proxi.DataExtractor >/dev/null 2>&1 &
    echo "Started Integration"    
    ;;    

*)
    echo "Usage: $prog {start}"    
    ;;    
esac    
exit 0   


//////////////////
#!/bin/bash    
#    
# tomcat startup script for the Tomcat server    
#    
# chkconfig: 345 80 20    
# description: start the tomcat deamon    
#    
# Source function library    
. /etc/rc.d/init.d/functions    

JAVA_HOME=/usr/local/java/jdk1.8.0_131  
export JAVA_HOME    
CATALANA_HOME=/home/instore/xueersi/apache-tomcat-8.5.15/  
export CATALINA_HOME
CATALANA_BASE=/home/instore/xueersi/store1/shopweb/ 

case "$1" in    
start)    
    echo "Starting Tomcat..."    
    $CATALANA_HOME/bin/startup.sh    
    ;;    

stop)    
    echo "Stopping Tomcat..."    
    $CATALANA_HOME/bin/shutdown.sh    
    ;;    

restart)    
    echo "Stopping Tomcat..."    
    $CATALANA_HOME/bin/shutdown.sh    
    sleep 2     
    echo    
    echo "Starting Tomcat..."    
    $CATALANA_HOME/bin/startup.sh    
    ;;    

*)    
    echo "Usage: $prog {start|stop|restart}"    
    ;;    
esac    
exit 0   




